### ISSUE TITLE
Every image filename is the same ("image.jpg")  making content saving or manual backup frustrating

### ISSUE THREAD

**Issue by spamcheck** [souperio/issues#4]

**Comment by severak** [comment]
I use md5 of file as filename in kyselo - e.g. https://kyselo.eu/pub/a7/52/ca/a752ca61a9c02f179d3ba595a3d270f3.jpg

It's short and sorta unique.

**Comment by v2px** [comment]
Fixed in souperio/souperio@8bd5dbc
